class_name CONSTANTES_GLOBAIS
extends Node

const Barra_de_vida:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistema de Vida/Cena/Barra_De_Vida.tscn")
const Barra_de_mana:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistema de Mana/Cena/Barra_De_Mana.tscn")
const Barra_de_estamina:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistema de Estamina/Cena/Barra_De_Estamina.tscn")
const Barra_De_Experiencia:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistema de experiencia/Cena/Barra_De_Experiencia.tscn")

const Maquina_de_estado:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Cena/MaquinaDeEstado.tscn")
const Parado:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Estados/Cena/Parado.tscn")
const Andando:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Estados/Cena/Andando.tscn")
const Pulando:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Estados/Cena/Pulando.tscn")
const NoAr:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Estados/Cena/NoAr.tscn")
const Aterrissando:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Estados/Cena/Aterrissando.tscn")
const Agachado:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Estados/Cena/Agachado.tscn")
const Correndo:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Estados/Cena/Correndo.tscn")
const Escalando:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Estados/Cena/Escalando.tscn")
const Morrendo:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Estados/Cena/Morrendo.tscn")
const Mirando:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Estados/Cena/Mirando.tscn")
const Combate:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Estados/Cena/Combate.tscn")
const CombateAndando:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Estados/Cena/CombateAndando.tscn")
const Esquivando:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Estados/Cena/Esquivando.tscn")
const CombateCorrendo:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/State Machine/Estados/Cena/CombateCorrendo.tscn")

const Valores_do_jogador:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Controladores/Cena/JogadorValores.tscn")
const Regulador_do_jogador:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Controladores/Cena/JogadorReguladores.tscn")
const Valores_do_inimigo:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Controladores/Cena/InimigoValores.tscn")
const Regulador_do_inimigo:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Controladores/Cena/InimigoReguladores.tscn")
const Sistema_de_dano:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistema de Dano/Cena/SistemaDeDano.tscn")

const Particula_de_pulo:PackedScene = preload("res://Matriz/Nucleo/Utilitarios/Particulas/Cena/particula_de_pulo.tscn")

const Ak40:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Amas de Longa Distancia/Armas Derivadas/Cena/Ak40.tscn")
const Ak41:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Amas de Longa Distancia/Armas Derivadas/Cena/Ak41.tscn")
const Ak42:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Amas de Longa Distancia/Armas Derivadas/Cena/Ak42.tscn")
const Ak43:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Amas de Longa Distancia/Armas Derivadas/Cena/Ak43.tscn")
const Ak44:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Amas de Longa Distancia/Armas Derivadas/Cena/Ak44.tscn")
const Ak45:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Amas de Longa Distancia/Armas Derivadas/Cena/Ak45.tscn")
const Ak46:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Amas de Longa Distancia/Armas Derivadas/Cena/Ak46.tscn")
const Ak47:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Amas de Longa Distancia/Armas Derivadas/Cena/Ak47.tscn")
const Ak48:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Amas de Longa Distancia/Armas Derivadas/Cena/Ak48.tscn")
const Ak49:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Amas de Longa Distancia/Armas Derivadas/Cena/Ak49.tscn")
const Ak50:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Amas de Longa Distancia/Armas Derivadas/Cena/Ak50.tscn")

const Xp:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistema de level Up/Xp/Cena/xp.tscn")
const Xp_Fraca:Texture2D = preload("res://Assets/Place Holder/Itens/Xp/Fraco.png")
const Xp_Medio:Texture2D = preload("res://Assets/Place Holder/Itens/Xp/Medio.png")
const Xp_Forte:Texture2D = preload("res://Assets/Place Holder/Itens/Xp/Forte.png")
const Xp_Muito_Forte:Texture2D = preload("res://Assets/Place Holder/Itens/Xp/Muito_Forte.png")

const Dinheiro:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Dinheiro/Cena/Dinheiro.tscn")

const Inimigo_Base:PackedScene = preload("res://Matriz/Nucleo/NPCs/Inimigos/Cena/inimigo_base.tscn")
const Personagem_Base:PackedScene = preload("res://Matriz/Nucleo/Personagem/Cena/Personagem.tscn")
const Camera_Controle:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Controladores/Cena/Camera.tscn")

const Arma_Basica_De_Ataque_Em_Area:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Armas de ataque em area/Cena/ArmaDeAtaqueEmArea.tscn")
const Tiro_De_Ataque_Em_Area:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Armas de ataque em area/Cena/TiroDeAtaqueEmArea.tscn")
const Gp10:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Armas de ataque em area/Armas Derivadas/Cena/GP10.tscn")
const Gp11:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Armas de ataque em area/Armas Derivadas/Cena/GP11.tscn")
const Gp12:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Armas de ataque em area/Armas Derivadas/Cena/GP12.tscn")
const Gp13:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Armas de ataque em area/Armas Derivadas/Cena/GP13.tscn")
const Gp14:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Armas de ataque em area/Armas Derivadas/Cena/GP14.tscn")
const Gp15:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Armas de ataque em area/Armas Derivadas/Cena/GP15.tscn")
const Gp16:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Armas de ataque em area/Armas Derivadas/Cena/GP16.tscn")
const Gp17:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Armas de ataque em area/Armas Derivadas/Cena/GP17.tscn")
const Gp18:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Armas de ataque em area/Armas Derivadas/Cena/GP18.tscn")
const Gp19:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Armas de ataque em area/Armas Derivadas/Cena/GP19.tscn")
const Gp20:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Armas de ataque em area/Armas Derivadas/Cena/GP20.tscn")

const Mostruario_de_armas:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Sistemas de Armas/Mostruario de Armas/Cena/MostruarioDeArmas.tscn")
const Ak40_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo1.png")
const Ak41_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo1.png")
const Ak42_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo1.png")
const Ak43_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo1.png")
const Ak44_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo1.png")
const Ak45_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo1.png")
const Ak46_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo1.png")
const Ak47_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo1.png")
const Ak48_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo1.png")
const Ak49_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo1.png")
const Ak50_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo1.png")
const Gp10_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo2.png")
const Gp11_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo2.png")
const Gp12_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo2.png")
const Gp13_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo2.png")
const Gp14_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo2.png")
const Gp15_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo2.png")
const Gp16_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo2.png")
const Gp17_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo2.png")
const Gp18_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo2.png")
const Gp19_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo2.png")
const Gp20_Mostruario:Texture2D = preload("res://Assets/Place Holder/Armas/free-guns-pixel-art/Amo2.png")

const Pocoes:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Pocoes/Cena/PocoesBase.tscn")
const Pocao_Vida_Pequena:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Pocoes/Pocoes Derivadas/Cena/PocaoVidaPequena.tscn")
const Pocao_Vida_Media:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Pocoes/Pocoes Derivadas/Cena/PocaoVidaMedia.tscn")
const Pocao_Vida_Grande:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Pocoes/Pocoes Derivadas/Cena/PocaoVidaGrande.tscn")
const Pocao_Mana_Pequena:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Pocoes/Pocoes Derivadas/Cena/PocaoManaPequena.tscn")
const Pocao_Mana_Media:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Pocoes/Pocoes Derivadas/Cena/PocaoManaMedia.tscn")
const Pocao_Mana_Grande:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Pocoes/Pocoes Derivadas/Cena/PocaoManaGrande.tscn")
const Pocao_Estamina_Pequena:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Pocoes/Pocoes Derivadas/Cena/PocaoEstaminaPequena.tscn")
const Pocao_Estamina_Media:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Pocoes/Pocoes Derivadas/Cena/PocaoEstaminaMedia.tscn")
const Pocao_Estamina_Grande:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Pocoes/Pocoes Derivadas/Cena/PocaoEstaminaGrande.tscn")
const Bomba:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Bombas/Cena/BombasBase.tscn")
const Ima:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Ima/Cena/Ima.tscn")
const Mata_Tudo:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Mata Tudo/Cena/MataTudo.tscn")
const Parar_Tempo:PackedScene = preload("res://Matriz/Nucleo/Sistema Motor/Consumiveis/Parar o Tempo/Cena/PararTempo.tscn")

const Interface_De_Abertura:PackedScene = preload("res://Matriz/Interfaces/Interface de abertura/Cena/Interface de abertura.tscn")
const Cena_Teste:PackedScene = preload("res://Matriz/Nucleo/Utilitarios/Cena Teste/Cena/nova_cena_teste.tscn")

const Interface_De_Selecao_De_Personagem:PackedScene = preload("res://Matriz/Interfaces/Interface de selecao de personagem/Cena/InterfaceDeSelecaoDePersonagem.tscn")
const Selecionador_De_Personagem:PackedScene = preload("res://Matriz/Interfaces/Interface de selecao de personagem/Mostruario de personagem/Cena/SelecionadorDePersonagem.tscn")
